- echiley.md
Oi Felipe Cezar facil demais o exercicio 
OBS: Não esquecemos o sorvete
> echiley respondeu a chamada

- ellen.md
Felipe, não estou entendendo nada
> Ellen respondeu a chamada

- mariarita.md
> Maria Rita respondeu a chamada

- Diovana.md
> Diovana responde a chamada

- jose.md
> José Victório respondeu  a chamada

- melyssa-julia.md
> Melyssa respondeu a chamada

- cmagno.md
> Carlos Magno respondeu a chamada

- lara.md
olá Felipe!!
Foi quase fácil!!
Ah, não passe exercícios muito grandes!!
Desde já agradeço.
Obrigada!
> Lara respondeu a chamada

- AnaMaria.md
OI Felipe,está atividade foi dificil pois o meu deu errado varias vezes.
OBS.:NÃO ESQUECEMOS DO SORVETE!!!!!!
> Ana Maria respondeu a chamada

- mariana.md
> Mariana respondeu a chamada

- Alexander.md
IFNMG -Campus Avançado Janaúba
> Alexander respondeu a chamada

- treyci.md
> Treyci respondeu a chamada

- Thaíla.md
> Thaíla respondeu a chamada

- amanda.md
> Amanda respondeu a chamada

- Isanna.md
> Isanna mudou

- raiane.md
parabéns felipe você é muito  #inteligente!!!!!!
> Raiane respondeu a chamada

- adila.md
> Ádila respondeu a chamada

- vitoria.md
> vitoria respondeu a chamada

- Andreza.md
Foi fácil de mais o exercício !!!
> Andreza respondeu a chamada

- larissa.md
Muito difícil é coisa de doido :+1:
> Larissa respondeu a chamada

- gabriel.md
> Gabriel respondeu a chamada

- jarbas.md
> Jarbas respondeu a sua chamada

- ronald.md
> Ronald respondeu a chamada

- thais-lorena.md
> Thais atendeu a chamada

- Emerson.md
> Emerson respondeu a chamada

- Joao.md
> joao respondeu a chamada
